addons:
  sonarcloud:
    organization: "deviyadh-1"
    token:
      secure: "573f48e6e1ba5a44f635f7b426ee4be822c99dec" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Deviyadh_Formation